[project]
name = 'flags'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.flags]
path = 'contracts/flags.clar'
clarity_version = 1
epoch = 2.0

[contracts.ownable]
path = 'contracts/ownable.clar'
clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
